version: 2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache: # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            echo "All Done Building"
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Test
          command: |
            pipenv run pytest
            echo "All Done Testing"

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
