version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            echo "All done"

workflows:
  version: 2
  workflow:
    jobs:
      - build
