version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            echo "All Done Building"
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Test
          command: |
            pytest
            echo "All Done Testing"

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
