version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache: # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            echo "All Done Building"
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.9/site-packages"
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache: # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Test
          command: |
            pipenv run pytest
            echo "All Done Testing"

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
